# Generated by Django 5.1.6 on 2025-02-14 23:03

import django.db.models.deletion
import django_prometheus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InsultCategory",
            fields=[
                (
                    "category_key",
                    models.CharField(
                        max_length=5, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Insult Category",
                "verbose_name_plural": "Insult Categories",
            },
        ),
        migrations.CreateModel(
            name="Insult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        error_messages="Insults must have content", max_length=65535
                    ),
                ),
                ("nsfw", models.BooleanField(default=False)),
                ("added_on", models.DateField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Active"),
                            ("X", "Inactive/Removed"),
                            ("P", "Pending"),
                            ("R", "Rejected"),
                        ],
                        default="P",
                        max_length=2,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="API.insultcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insult/Joke",
                "verbose_name_plural": "Insults/Jokes",
                "db_table": "insults",
                "ordering": ["nsfw", "category"],
                "managed": True,
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("insult"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="InsultReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anonymous", models.BooleanField(default=False)),
                (
                    "reporter_first_name",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "reporter_last_name",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("post_review_contact_desired", models.BooleanField(default=False)),
                (
                    "reporter_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("date_submitted", models.DateField(auto_now=True)),
                ("date_reviewed", models.DateField(blank=True, null=True)),
                ("rationale_for_review", models.TextField()),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("RE", "Joke Reclassification"),
                            ("RC", "Joke Recategorization"),
                            ("RX", "Joke Removal"),
                        ]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("P", "Pending"),
                            ("NCE", "Completed - New Explicitly Setting"),
                            ("SCE", "Completed - No New Explicitly Setting"),
                            ("NJC", "Completed - Assigned to New Category"),
                            ("SJC", "Completed - No New Category Assigned"),
                            ("X", "Completed - Joke Removed"),
                        ],
                        default="P",
                        null=True,
                    ),
                ),
                (
                    "insult_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="API.insult"
                    ),
                ),
            ],
            options={
                "verbose_name": "Joke Needing Review",
                "verbose_name_plural": "Jokes Needing Review",
                "db_table": "reported_jokes",
                "ordering": ["status", "-date_submitted"],
                "get_latest_by": ["-date_submitted"],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("jokeReview"),
                models.Model,
            ),
        ),
        migrations.AddIndex(
            model_name="insult",
            index=models.Index(fields=["category"], name="idx_category"),
        ),
        migrations.AddIndex(
            model_name="insult",
            index=models.Index(fields=["category", "nsfw"], name="idx_nsfw_category"),
        ),
        migrations.AddIndex(
            model_name="insult",
            index=models.Index(fields=["nsfw"], name="idx_nsfw"),
        ),
        migrations.AddIndex(
            model_name="insult",
            index=models.Index(fields=["added_by"], name="idx_added_by"),
        ),
    ]
