-- Initial Data Load. Contains all the initial jokes and joke CATEGORIES
-- In Production - This will be replace with a routine backup snapshot of the database, that should be used for recovery efforts

--Clear Categories to Avoid Duplication
DELETE FROM insult_categories;

INSERT INTO insult_categories (category_key, name) VALUES ('DO', 'Daddy - Old');
INSERT INTO insult_categories (category_key, name) VALUES ('DS', 'Daddy - Stupid');
INSERT INTO insult_categories (category_key, name) VALUES ('F', 'Fat');
INSERT INTO insult_categories (category_key, name) VALUES ('H', 'Hairy');
INSERT INTO insult_categories (category_key, name) VALUES ('L', 'Lazy');
INSERT INTO insult_categories (category_key, name) VALUES ('N', 'Nasty');
INSERT INTO insult_categories (category_key, name) VALUES ('O', 'Old');
INSERT INTO insult_categories (category_key, name) VALUES ('P', 'Poor');
INSERT INTO insult_categories (category_key, name) VALUES ('SKN', 'Skinny');
INSERT INTO insult_categories (category_key, name) VALUES ('SNWF', 'One-Off');
INSERT INTO insult_categories (category_key, name) VALUES ('T', 'Tall');
INSERT INTO insult_categories (category_key, name) VALUES ('TEST', 'INTERNAL - TEST');
INSERT INTO insult_categories (category_key, name) VALUES ('U', 'Ugly');


-- Clear Current Jokes to Avoid Duplication
DELETE FROM insults;


-- Joke Insertion START
INSERT INTO insults (content, nsfw, added_on, last_modified, status, added_by_id, category_id) VALUES
('Yo momma so dumb it takes her twenty minutes to cook minute rice.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat she needs two watches for two different time zones.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma''s feet are so big... her shoes have to have license plates!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so poor when I saw her kicking a can down the street, I asked her what she was doing, she said “Moving.”', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb, she failed a survey.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old she still owes Moses money.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so ugly... her mom had to tie a steak around her neck to get the dogs to play with her.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is cross-eyed and watches TV in stereo.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so stupid... she sold her car for gas money.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb, it takes her an hour to cook minute rice.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... she has a picture of Moses in her yearbook.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... I told her to act her own age, and she died.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('TEST - This Document Shoulds be Found by explicit: true', TRUE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so angry, that McDonalds won''t even serve her happy meals.,', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so ugly, when she was born the doctor slapped your grandma!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... I walked in her house and stepped on a cigarette, and your mom said, ''Who turned off the lights?''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... I stepped in her house and I was in the backyard.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so stupid... she can''t pass a blood test.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so ugly... for Halloween she trick-or-treats on the phone!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma''s glasses are so thick she can look at a map and see people waving.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so stupid... it took her 2 hours to watch 60 seconds.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so big, when she talks to herself it’s a long-distance call.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so tall... Shaq looks up to her.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, she gets group insurance!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so stupid, when they said ''Order in the court'', she asked for fries and a shake.,', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... that her bus pass is in hieroglyphics!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so ugly, her own portraits hang themselves.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma’s teeth are so yellow, when she smiles, she puts the sun out of business.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she rolled out of bed and everybody thought there was an earthquake.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... the roaches pay the light bill!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... people jog around her for exercise.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so stupid... when they said that it is chilly outside, she went outside with a bowl and a spoon.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so stupid... when she asked me what kind of jeans am I wearing I said, ''Guess'', and she said, ''Levis''.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so confusing even Scooby Doo can''t figure her out!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... every time she walks in high heels, she strikes oil!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma''s glasses are so thick... she can see into the future.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so short... she has a job as a teller at a piggy bank.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat when she goes camping, the bears hide their food.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when she took her shirt off at the strip club, everyone thought she was Jabber the Hut from Star Wars.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... that when she wanted a waterbed, they had to put a cover over the Atlantic Ocean.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... she can''t afford to pay attention!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma house so small, you have to go outside to change your mind.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so ugly, she could scare the chrome off a bumper!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat that when she hauls ass, she has to make two trips!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so lazy, she stuck her nose out the window so the wind could blow it.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so ugly, she could scare the moss off a rock!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so bald... she had to braids her beard.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so old, when she was born, the Dead Sea was still just getting sick.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so ugly, when she walks into the dentist, they make her lay face down.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so ugly... just after she was born, her mother said, ''What a treasure!'' And her father said, ''Yes, let''s go bury it!''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when she has wants someone to shake her hand, she has to give directions!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so ugly... when she walks into a bank, they turn off the surveillance cameras.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old her driver''s license is written with Roman numerals.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo daddy so old, his Social Security number is 4.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma arms are so hairy, when she walks down the street it looks like she has Buckwheat in a headlock.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma’s so fat, when she stepped on the scale it said, ‘To be continued.’', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when a bus hit her she said, ''Who threw the pebble?''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so old, she walked into an antique store and they kept her.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb, she cooked her own complimentary breakfast.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so ugly... the government moved Halloween to her birthday.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so nasty... cows with mad cow disease run from her.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, when she takes a shower, her feet don’t get wet!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she was floating in the ocean and Spain claimed her for the new world!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when her beeper goes off, people think she is backing up.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so short ... she poses for trophies!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat that when she sat on an iPhone it turned into an iPad.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so old, when she was young, rainbows were still black and white.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... I stepped in her house and I was in the backyard.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb when your dad said it was chilly outside, she ran outside with a spoon.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma''s teeth are so yellow... that when she smiles everyone sings, ''I got sunshine on a cloudy day''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when she dives into the ocean, there is a tsunami-warning!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so scary, even Voldemort won’t say her name.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old she has a picture of Abraham carved into her yearbook.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... she knew the Great Wall of China when it was only good!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when she jumps up in the air she gets stuck!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so skinny... she turned sideways and disappeared.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so tall... she tripped over a rock and hit her head on the moon.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so bald, you can see what’s on her mind.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... she was wearing a Jesus starter jacket!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so ugly... when she walks down the street in September, people say ''Wow, is it Halloween already?''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... the highway patrol made her wear ''Caution!, Wide Turn!''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she broke a branch in her family tree!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat when she tried to weight herself and the scales said ''one at a time please''. ', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma''s nose is so big... she makes Pinocchio look like a cat!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so poor, ducks throw bread at her.', TRUE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so ugly she walked into a haunted house and walked out with a job application.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so stupid... she put lipstick on her forehead to make up her mind.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... her birth certificate says expired on it.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so stupid she thought light sabers had less calories.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... that when she was in school there was no history class.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so short... she uses a toothpick as pool stick.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so poor when she goes to the park, ducks throw bread at her!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so bald... Mr. Clean was jealous.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so old, Jurassic Park brings back memories.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so skinny... she swallowed a meatball and thought she was pregnant.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so short, she went to see Santa and he told her to get back to work.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so short... she can use a sock for a sleeping bag.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when she steps on a scale, it read, ''cone at a time, please''d.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so tall... she can see her home from anywhere.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, she fell in love</a> and broke it.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat that when she walked past the TV I miss three episodes.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb, she went to the library to find Facebook.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, a picture of her would fall off the wall!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, she makes Godzilla look like an action figure.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she makes Godzilla look like an action figure.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is nasty. When she went to take a bath, the water jumped out and said, ''That''s okay, I''ll wait.''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... she knew Burger King while he was still a prince.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... I stepped in her house and I was in the backyard.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma''s head is so small... she uses a tea bag as a pillow.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so hairy... she has cornrows on her back, legs, and feet!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she walked in front of the TV and I missed 3 shows.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, she wakes up on both sides of the bed.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat that her official job title is spoon and fork operator.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so strict, she locked you up in a tower.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('TEST - This Document Shoulds be Found by Catagory: ''Test''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she supplies 99% of the world''9s gas.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so skinny... she can hang glide with a Dorito!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb that she spent hours starting at a glass of orange juice because it said ''concentrate'' on the package.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so nasty she swam the Ink Sea and left a dark streak.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old she helped write the ten commandments.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... her measurements are 26-34-28, and her other arm is just as big!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so lazy... she thinks a two-income family is where the man has two jobs.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when she bungee jumps, she brings down the bridge too.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so tall... she tripped in Denver and hit her head in New York.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she''s got her own area code!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... her birth certificate is in Roman numerals.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma''s cooking is so bad even the homeless send it back.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so lazy... she''s got a remote control just to operate her remote!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so old she still owes Moses a quarter!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... she ran track with dinosaurs.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old she cleaned up after the last supper.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('“Yo momma’s so ugly she went into a haunted house and they handed her an application.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so old, her birth certificate is in Roman numerals.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she has more chins than a Chinese phone book.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so skinny... she can see through peepholes with both eyes.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, I took a picture of her last Christmas and the damn thing''s still printing.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when she goes to an amusement park, people try to ride her!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so stupid... she stole free bread.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so lazy she woke up from a coma and went to sleep.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so stupid... she stopped at a stop sign and waited for it to turn green.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she had her ears pierced by harpoon.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, if she got her shoes shined, she’d have to take his word for it!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb, when the doctor told her she had coronavirus, she bought a new laptop.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... when I saw her kicking a can down the street, I asked her what she was doing, she said, ''Moving''.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so stupid, she climbed over a glass wall to see what was on the other side.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat she can’t reach her back pocket.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when she was in school she sat next to everybody!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when she went bungee jumping in a yellow dress, everyone was screaming the suns falling!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb, she put sugar on the bed because she wanted sweet dreams.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('TEST - This Document Shoulds be Found by Catagory: ''Test''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so old, she was a waitress at the Last Supper.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, she uses Google Earth to take a selfie.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so ugly... when they took her to the beautician it took 12 hours for a quote!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb when you stand next to her you hear the ocean!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so ugly, even Hello Kitty said goodbye.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... I walked in her house and stepped on a cigarette, and your mom said, ''Who turned off the lights?''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so small... that she got her ear pierced and died.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so lazy she stands outside to let the wind blow her nose!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... she waves around a popsicle stick and calls it air conditioning.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so ugly, she made an onion cry.,', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so ugly, her birth certificate is an apology letter.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so bald... everyone thought the sun was rising when she got up.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when she wore a blue and green sweater, everyone thought she was Planet Earth.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... it took me a bus and two trains just to get on her good side.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so lazy... that she came in last place in a recent snail marathon.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so ugly, she went into a haunted house and the ghosts ran away.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma’s so stupid she thought fortnite was fork night.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... you could use her bellybutton as a wishing well.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('TEST - Document Should Be Found By explicit: True and Status: ''Deleted''', FALSE, '2025-08-02', NULL, 'X', 1, 'SNWF'),
('Yo momma so fat, her job title is Spoon and Fork Operator!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she had to be baptized at sea world.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so stupid that she thought Star Wars was a war for stars.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so skinny... she uses cotton balls for pillows.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo mo''mma is so ugly... she got beat up by her imaginary friends!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb, she called me to ask for my phone number.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so ugly... she made an onion cry.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so skinny... she can dive through a chain-linked fence.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she rolled over 4 quarters and made a dollar!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... her birth certificate says expired on it.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so short... she can surf on a popsicle stick.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('“Yo momma’s so fat that when she walked past the TV, I missed three episodes.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb, she trips over the wireless internet.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... NASA has to orbit a satellite around her!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she uses an air balloon for a parachute.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... she was in Walmart with a box of Hefty bags. ''I said, what ya doing?'', She said, ''Buying luggage.''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so stupid, she returned a doughnut because it had a hole in it.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she has seat belts on the chairs to keep her fat from rolling off!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... the roaches pay the light bill!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so stupid, she got locked in a mattress store and slept on the floor.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when she turns around they throw her a welcome back party.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so hairy... the zoo offered to buy her kids.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so lazy, she has a stay-at-home job and still is late to work.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so bald... that she took a shower and got brainwashed.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, Thanos had to clap.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... her nickname is Lardo.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, she left in high heels and came back in flip flops.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she put on her lipstick with a paint roller.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she sat on a rainbow and made skittles.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... when I saw her kicking a can down the street, I asked her what she was doing, she said, ''Moving''.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... the back of her neck is like a pack of hot dogs!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... whenever she goes to the beach the tide comes in!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb, she tried to eat Eminem!,', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... her husband has to stand up in bed each morning to see if it''s daylight!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when she puts on her yellow rain coat and walks down the street people shout out ''ctaxi''d!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb she sold her car to get gasoline money!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma''s house is so small... you have to go outside to change your mind.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so clumsy... she got tangled up in a cordless phone.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb, she thought Twitter was social media for birds.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so stupid... she worked at a M&M factory and threw out all the W''s.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so poor she can’t even pay attention.', TRUE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so stupid, she studied for a Covid test.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... she ran track with dinosaurs.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma''s hair is so short she rolls it with rice.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so skinny... she has to run around in the shower just to get wet.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so ugly, she walked into a Haunted House and walked back out with a job application.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old she knew burger king when he was still a prince.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so stupid... she got locked in Furniture World and slept on the floor.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so hairy... she shaves with a weed-eater.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when she goes to Taco Bell, they run for the border!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma''s teeth are so yellow... I can''t believe it''s not butter.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('“Yo momma’s so stupid she told me to meet her at the corner of Walk and Don’t Walk.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so short ... she has to use a ladder to pick up a dime.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
(' Yo momma so fat when she got on the scale it said, ''I need your weight not your phone number''.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, when she crossed the road people mistook her for a roundabout.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when she wears a red dress all the kids scream look it''9s the Kool-Aid man.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... her social security number is 1!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, she goes to the car wash to take showers.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so stupid... she tried to commit suicide by jumping out the basement window.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so tall... she did a cartwheel and kicked the gates of Heaven.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma''s head is so big... it shows up on radar.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo daddy so dumb, somebody said it was chilly outside so he went to get a bowl.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma''s feet are so scaly... you can see Crocodile Dundy in her footbath.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so stupid... she sits on the floor and watches the couch.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, when she buys a fur coat, a whole species goes extinct.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... she can''t afford to pay attention!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so hairy... that Bigfoot tried to take her picture!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma''s head is so big... she has to step into her shirts.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so ugly, she made an onion cry.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, and old, that when God said ''Let there be light,'' he was just asking her to move out of the way.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when she plays hopscotch, she goes North America, Europe, Asia.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so skinny... she hula hoops with a cheerio.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, when God said, “Let there be light,” he asked her to move out of the way.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma has so many chins... it looks like she''s wearing a fat necklace!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old she got sold while looking around the antique store!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so lazy... she starved instead of getting up to get some food.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, that when she hauls ass it takes her two trips.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so old, her driver’s license got hieroglyphics on it!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when God said, ''cLet there be light,''d he had to ask her to move out of the way.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so short ... she can play handball on the curb.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so ugly, when she looks in the mirror, her reflection ducks.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma ain''t got no ears yelling... Let me hear both sides of the story!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... the government forced her to wear taillights and blinkers so no one else would get hurt.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... the last time she saw 90210 was on the scale!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she needs a watch on both arms because she covers two time zones.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so old, she knew Burger King when he was a prince.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo daddy is so dumb he turned down a blowjob because he thought it would mess up his unemployment check.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so ugly... when she joined an ugly contest, they said, ''Sorry, no professionals.''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she lays on the beach and people run around yelling Free Willy!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so ugly, people dress up as her for Halloween.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb, when she heard about cookies on the Internet, she ate her computer.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old she took her driving test on a triceratops!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, even Dora can’t explore her.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so stupid... she ordered a cheeseburger without the cheese.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so bald... even a wig wouldn''t help!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so old, her birth certificate says expired on it.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so ugly... she tried to take a bath and the water jumped out!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma''s nose is so big... that her neck broke from the weight!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... when her friend came over to use the bathroom she said, ''Ok, choose a corner.''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old her first car was a chariot!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so clumsy, she makes Humpty Dumpty look like a gymnast.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat she sat on a dollar and when she got up there was 4 quarters.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma''s house is so poor... I went to knock on her door and a roach tripped me and a rat took my wallet!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is like the sun... you look at her to long you will go blind!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, when she walked past the TV, I missed three episodes.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she uses the interstate as a slip and slide.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so stupid, she took a ruler to bed to see how long she slept.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... she waves around a popsicle stick and calls it air conditioning.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma''s teeth are so yellow... that when she smiles traffic slows down.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so ugly that the government moved Halloween to be on her birthday.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when she steps on the scale it says we don''t do livestock.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... I walked in her house and stepped on a cigarette, and your mom said, ''Who turned off the lights?''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she sat on a tractor and made a pick-up truck.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so skinny... her nipples touch.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, she was floating in the ocean and Spain claimed her for their new world.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she sank the Titanic!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... her social security number is 1!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so short... she can sit on a dime and swing her legs.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so hairy... she wears a Nike tag on her weave so now everybody calls her Hair Jordan.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma''s glasses are so thick... that when she looks on a map she can see people waving.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so stupid... that she burned down the house with a CD burner.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... she has a picture of Moses in her yearbook.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb, she thought KFC was UFC for chickens.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma''s mouth is so big... she speaks in surround sound.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... when her friend came over to use the bathroom she said, ''Ok, choose a corner.''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... she can''t afford to pay attention!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat that when she orders a fur coat an entire species goes extinct.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, when she gets in an elevator, it HAS to go down!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so old, when someone told her to act her age, she died.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so stupid when thieves broke into her house and stole the TV, she chased after them shouting ''Wait! You forgot the remote!'',', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so stupid, she sold the house to pay the mortgage.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb, she put a watch in a piggybank and said she was saving time.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... when I saw her kicking a can down the street, I asked her what she was doing, she said, ''Moving''.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma house so small that when she orders a large pizza, she has to go outside to eat it.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so hairy... Harry Potter got jealous.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she eats Wheat Thicks.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat that her belt size is ''equator''!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so stupid, she couldn’t read an audiobook.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... she knew Burger King while he was still a prince.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so short... she can tie her shoes while standing up.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so hairy... you almost died of rug burn at birth!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she goes to a restaurant, looks at the menu, and says, ''okay!''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so stupid... she got locked in a grocery store and starved.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat that she needs to take our group insurance when she travels.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma’s glasses are so thick, when she looks at a map, she can see people waving at her.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so ugly, her birth certificate is an apology letter from the condom factory.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is missing a finger and can''t count past nine.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so old, she walked into an antiques store, and they didn’t let her leave.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... her birth certificate is in Roman numerals.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma''s house is so small... that when she orders a large pizza she had to go outside to eat it.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... she was in Walmart with a box of Hefty bags. ''I said, what ya doing?'', She said, ''Buying luggage.''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... the roaches pay the light bill!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so ugly that she has to trick or treat over the phone.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she makes a whale look bulimic!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat when she tripped over on 4th Ave, she landed on 12th.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... when I ring the doorbell she says, ''[DING!''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat that even Dora don''t have time to explore her!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so ugly, she turned Medusa to stone.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... I told her to act her own age, and she died.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so skinny... she has to wear a belt with her spandex pants.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is in a wheelchair and says... ''You ain''t gonna push me around no more!''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb that she thought, Dunkin'' Donuts was a basketball team!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, when she got hit by a bus she asked, “Who threw that rock?”', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when she sits on the beach, whales swim up to her and sing we are family...!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so ugly, when she was born the doctor slapped her parents.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she looks like she''s smuggling an SUV!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma’s so short when she plays fortnite she can hide under the freaking store.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so tall... she 69''d bigfoot.', TRUE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so ugly... The NHL banned her for life.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so tall... she has to take a bath in the ocean.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... when I ring the doorbell she says, ''[DING!''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she jumped in the air and got stuck.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... when I ring the doorbell she says, ''[DING!''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... that she needs a bookmark to keep track of all her chin rolls!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so ugly... she gets 364 extra days to dress up for Halloween.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so ugly... that your father takes her to work with him so that he doesn''t have to kiss her goodbye.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so ugly... even Rice Krispies won''t talk to her!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb she thought a quarterback was a refund.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so ugly... she turned Medusa to stone!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she went to the movies and sat next to everyone.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... that her bus pass is in hieroglyphics!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma’s head so big, she dreams in IMAX.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so confusing, even Scooby Doo couldn’t solve that mystery.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so stupid... she got lost in a telephone booth.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so ugly,  even hello kitty said ''goodbye''!,', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so short... she does backflips under the bed.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so old, when the preacher asked if she knew Jesus, she said, ''Know him? Motherfucker still owes me five dollars.''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so hairy people think she’s an Ewok.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb she cooks her own complimentary breakfast.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so skinny... she don’t get wet when it rains.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so hairy... her tits look like coconuts.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... she was wearing a Jesus starter jacket!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so grouchy... the McDonald''s she works at doesn''t even serve happy meals.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... she waves around a popsicle stick and calls it air conditioning.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she was going to Wal-Mart, tripped over Kmart, and landed right on Target!!!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when she bungee jumps she goes straight to hell!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when she lays on the beach no one else gets sun!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so mean, they don’t give her happy meals at McDonalds.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so ugly that her portraits hang themselves.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so tall... she high-fived God.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, she left in high heels and came back in flip flops.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so short... she has to use rice to roll her hair up.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb, she puts lipstick on her forehead to make-up her mind.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so ugly, she makes blind kids cry.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she jumped off the Grand Canyon and got stuck.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... your family ate cereal with a fork to save milk.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb, she tried to eat Eminem the rapper.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so ugly... that she scares blind people!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... she was in Walmart with a box of Hefty bags. ''I said, what ya doing?'', She said, ''Buying luggage.''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when she takes a bath she fills the tub then turns on the water.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so ugly, she has a sign in her garden saying, ‘Beware of the dog!’', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, when stepped on the scale it said, ‘To be continued.’', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... she knew the Great Wall of China when it was only good!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so nasty, she went swimming and made the Dead Sea.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so ugly... instead of putting the bungee cord around her ankle, they put it around her neck.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... they had to install speed bumps at all you can eat buffets.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so bald... you can see what''s on her mind.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat she poured two drops of water into the tub and got it. It still overflowed.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she''s got to wake up in sections.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so ugly... they didn''t give her a costume when she tried out for Star Wars.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when she gets on the elevator it says, ''cNext stop, Hell''d!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so stupid, she went to the dentist to get Bluetooth.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma’s teeth so yellow, when she drinks water, it turns into lemonade.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so chatty, she gave a eulogy at her own funeral.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so dumb, she got fired from the M &amp; M factory for throwing away all the W’s.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... she fell and made the Grand Canyon!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so fat... when you go around her you get lost!', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so old... that when she was in school there was no history class.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so poor... when her friend came over to use the bathroom she said, ''Ok, choose a corner.''', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma is so lazy... she arrived late at her own funeral.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF'),
('Yo momma so fat, when she skips a meal, the whole stock market drops.', FALSE, '2025-08-02', NULL, 'A', 1, 'SNWF');