version: '3'
env:
  DOPPLER_TOKEN: ${DOPPLER_TOKEN}
  PATH_TO_DB_ROOT_CERT: ${PATH_TO_DB_ROOT_CERT}
  PYTHON_PATH: "{{ .TASKFILE_DIR }}:$(pwd)/applications/API:$(pwd)/applications/graphQL:$(pwd)/applications/frontend:$(pwd)/common:$(pwd)/run"

silent: true
tasks:
  default:
    cmds:
      - task -l
    silent: true

  venv:
    desc: Make a new virtual environment
    cmds:
      - python3 -m venv .venv --prompt="ACTIVE_VENV_DJANGO_DOZENS"
      - source {{.TASKFILE_DIR}}/.venv/bin/activate
    internal: true
  
  develop:
    desc: Starts the Django Application, and background workers in a debug state
    dir: .
    cmds:
      - echo "Completing Pre-Start Environment Check For Development..."
      - source .envrc && PYTHONPATH="./core:$(pwd)/applications/API:$(pwd)/applications/graphQL:$(pwd)/applications/frontend:$(pwd)/common:$(pwd)/run:$(pwd)" doppler run  -- python3 .venv/bin/gunicorn -t 30 -w 3 --timeout 120 --worker-class=sync core.wsgi:application --bind 127.0.0.1:{{.CLI_ARGS}} --reload
    interactive: false
    silent: false


  install:
    deps: [venv]
    cmds:
      - pip install poetry
      - poetry lock
      - poetry install --no-root
    silent: false

  freeze:
    desc: Pin current dependencies
    cmds:
      - doppler run  -- poetry sync
      - doppler run  -- poetry export --without dev,test --without-hashes --without-urls > ./requirements/base.txt
      - doppler run  -- poetry export  --without-hashes --without-urls > ./requirements/dev.txt
    generates:
      - ./requirements/dev.txt
      - ./requirements/base.txt
      - ./poetry.lock
    sources:
      - ./poetry.lock
      - ./requirements/dev.txt
      - ./requirements/base.txt
    silent: false

  db_sync:
    desc: Make and run migrations
    dir: .
    cmds:
      - doppler run --  python3 run/manage.py makemigrations
      - doppler run --  python3 run/manage.py migrate
    generates:
      - ./application/migrations/*.py
    sources:
      - .application/migrations/*.py
    requires:
      vars:
        - DOPPLER_TOKEN
        - PATH_TO_DB_ROOT_CERT

  collect:
    dir: .

    desc: Collect static files in to single directory for production
    cmds:
      - source .envrc && PYTHONPATH="./core:$(pwd)/applications/API:$(pwd)/applications/graphQL:$(pwd)/applications/frontend:$(pwd)/common:$(pwd)/run:$(pwd)" doppler run -- python run/manage.py collectstatic --no-input

  test:
    dir: .
    desc: Run tests
    cmds:
      - doppler run --  python3 run/manage.py test applications.API
    requires:
      vars:
        - DOPPLER_TOKEN
        - PATH_TO_DB_ROOT_CERT

  run:
    desc: Starts a Gunicorn Based Development Server that Reloads on Changes
    dir: .

    cmds:
      - doppler run -- python3 run/manage.py runserver #--workers=2 --threads=2 core.wsgi:application -b :{{or .CLI_ARGS 8000}} --reload
    requires:
      vars:
        - DOPPLER_TOKEN
        - PATH_TO_DB_ROOT_CERT


  start:
    dir: .

    desc: Command to Start Production Level Services including Install requirements, apply migrations, then start development server
    cmds:
      - echo 'Starting Production Level Services...'
      - echo 'Installing dependencies'
      - task: install

      - echo 'Applying migrations...'
      - task: db_sync

      - echo 'Starting server...'
      - doppler run -- python3 -m gunicorn --workers=2 --threads=2 core.wsgi:application --bind 0.0.0.0:{{or .CLI_ARGS 8080}} --reload --sync

  schema-check:
    dir: /Users/terry-brooks./Github/the-dozens-django

    desc: Check Models and Serializers for schema compliance with OpenAPI .0 Standards and fail on warnings
    cmds:
      - doppler run --  python3 run/manage.py spectacular  --file schema/schema$(date +"%Y-%m-%d").yaml --validate
    internal: true

  schema:
    deps: [schema-check]
    dir: /Users/terry-brooks./Github/the-dozens-django

    desc: Generate OpenAPI 3.0 schema.yaml file from models and serializers
    cmds:
      - doppler run --  python3 run/manage.py spectacular --file schema/schema$(date +"%Y-%m-%d_%H:%M:%S").yaml

  build-image:
    desc: Build Docker Image
    dir: /Users/terry-brooks./Github/the-dozens-django/.deploy
    cmds:
      - docker build buildx --platform --push linux/amd64,linux/arm64  --env DOPPLER_TOKEN=$DOPPLER_TOKEN -t thedozens:latest .
    requires:
      vars:
        - DOPPLER_TOKEN
        - PATH_TO_DB_ROOT_CERT

  lint:
    desc: Run linters
    dir: /Users/terry-brooks./Github/the-dozens-django

    cmds:
      - python3 -m black .
      - python3 -m isort --profile black .
      - python3 -m autoflake --remove-all-unused-imports --recursive --remove-unused-variables --in-place .

