"""
Custom DRF authentication classes for the API.

Provides a flexible TokenAuthentication subclass that accepts both
the standard ``Token <key>`` format and a bare ``<key>`` value in the
Authorization header.  The latter is required for clients that follow
the OpenAPI ``apiKey`` security-scheme definition generated by
drf-spectacular.
"""

from rest_framework.authentication import TokenAuthentication


class FlexibleTokenAuthentication(TokenAuthentication):
    """Accept ``Authorization: Token <key>`` *and* ``Authorization: <key>``.

    DRF's built-in ``TokenAuthentication`` requires the ``Token`` keyword
    prefix.  However, the OpenAPI schema advertises an ``apiKey``
    security-scheme that causes Swagger-UI (and other spec-driven
    clients) to send the bare token value without the keyword.

    This subclass falls back to treating a single-part Authorization
    header value as the token key itself, so both formats work.
    """

    def authenticate(self, request):
        # Try the standard ``Token <key>`` path first.
        result = super().authenticate(request)
        if result is not None:
            return result

        # Fallback: treat a bare Authorization value as the token key.
        from rest_framework.authentication import get_authorization_header
        auth = get_authorization_header(request).split()

        if len(auth) == 1:
            token = auth[0].decode()
            return self.authenticate_credentials(token)

        return None
