"""
applications.frontend.tests.test_report_view
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Tests for ReportJokeView — the joke-reporting endpoint that validates an
InsultReview payload and opens a GitHub issue via ``settings.BASE.get_github_api()``.

Coverage
--------
ReportJokeView.post()
  * Valid anonymous submission → HTTP 201, {"status": "SUCCESS"}
  * Valid named (non-anonymous) submission → HTTP 201, {"status": "SUCCESS"}
  * GitHub issue title follows the expected format
  * GitHub issue body equals the submitted rationale
  * Rationale shorter than 70 characters → HTTP 400
  * Non-anonymous submission with missing first/last name → HTTP 400
  * Post-review contact requested but no email provided → HTTP 400
  * Unknown insult reference_id → HTTP 400
  * GitHub API raises an exception → HTTP 422, status key starts with "FAILED"
  * GitHub create_issue() is NOT called when the payload is invalid

ReportJokeView.format_issue()
  * Returns dict with exactly the keys "issue_title" and "issue_body"
  * Title embeds the reference_id and review_type
  * Body equals the raw rationale_for_review text
  * Raises ValueError when passed a non-dict

Notes
-----
* ``setUp()`` clears the cache before every test to reset DRF throttle
  counters — without this, the anon rate limit (1/minute in Testing) causes
  429 responses on every test after the first.
* ``OpenReportJokeView`` sets ``throttle_classes = []`` to prevent the
  throttle from firing at all, giving each test a clean slate regardless of
  cache state or run order.
"""

from unittest.mock import MagicMock, patch

from django.contrib.auth import get_user_model
from django.core.cache import cache
from django.test import TestCase
from django.utils import timezone
from rest_framework import status
from rest_framework.test import APIRequestFactory

from applications.API.models import Insult, InsultCategory, InsultReview, Theme
from applications.frontend.views import ReportJokeView

User = get_user_model()

# ---------------------------------------------------------------------------
# Minimum valid rationale (serializer requires >= 70 characters)
# ---------------------------------------------------------------------------
_RATIONALE = (
    "This joke is deeply offensive and targets a protected group in a harmful "
    "manner that violates community standards."
)

assert len(_RATIONALE) >= 70, "Test fixture rationale must be at least 70 characters."


# ---------------------------------------------------------------------------
# Throttle-free view subclass
# ---------------------------------------------------------------------------


class OpenReportJokeView(ReportJokeView):
    """ReportJokeView with throttling disabled for test isolation."""

    throttle_classes = []
    authentication_classes = []
    permission_classes = []
    queryset = InsultReview.objects.all()

# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------


def _post(factory: APIRequestFactory, payload: dict):
    """Dispatch a POST through the throttle-free view."""
    view = OpenReportJokeView.as_view()
    req = factory.post("/api/", payload, format="json")
    return view(req)


# ---------------------------------------------------------------------------
# Main test class
# ---------------------------------------------------------------------------


class ReportJokeViewTests(TestCase):
    """End-to-end tests for POST /api/ → ReportJokeView."""

    @classmethod
    def setUpTestData(cls):
        cls.owner = User.objects.create_user(
            username="joke_owner",
            email="owner@example.com",
            password="pass1234",
        )
        cls.theme = Theme.objects.create(theme_key="TST", theme_name="Test Theme")
        cls.category = InsultCategory.objects.create(
            category_key="P",
            name="Poor",
            theme=cls.theme,
        )
        cls.insult = Insult.objects.create(
            content=(
                "Yo momma is so poor she chases the garbage truck with a shopping list."
            ),
            category=cls.category,
            nsfw=False,
            theme=cls.theme,
            status=Insult.STATUS.ACTIVE,
            added_by=cls.owner,
            added_on=timezone.now(),
        )
        # reference_id is auto-generated by a post_save signal
        cls.insult.refresh_from_db()

        cls.factory = APIRequestFactory()

    def setUp(self):
        """Clear the cache before every test to reset DRF throttle counters."""
        cache.clear()

    # ------------------------------------------------------------------
    # Happy-path: anonymous submission
    # ------------------------------------------------------------------

    @patch("applications.frontend.views.settings")
    def test_anonymous_report_returns_201(self, mock_settings):
        """A valid anonymous report returns HTTP 201 with status SUCCESS."""
        mock_settings.BASE.get_github_api.return_value = MagicMock()

        payload = {
            "insult_reference_id": self.insult.reference_id,
            "anonymous": True,
            "review_type": InsultReview.REVIEW_TYPE.REMOVAL,
            "rationale_for_review": _RATIONALE,
        }
        resp = _post(self.factory, payload)

        self.assertEqual(resp.status_code, status.HTTP_201_CREATED)
        self.assertEqual(resp.data["status"], "SUCCESS")

    @patch("applications.frontend.views.settings")
    def test_anonymous_report_calls_create_issue(self, mock_settings):
        """A valid anonymous report calls GitHub create_issue() exactly once."""
        mock_gh = MagicMock()
        mock_settings.BASE.get_github_api.return_value = mock_gh

        payload = {
            "insult_reference_id": self.insult.reference_id,
            "anonymous": True,
            "review_type": InsultReview.REVIEW_TYPE.REMOVAL,
            "rationale_for_review": _RATIONALE,
        }
        _post(self.factory, payload)

        mock_gh.create_issue.assert_called_once()

    # ------------------------------------------------------------------
    # Happy-path: named (non-anonymous) submission
    # ------------------------------------------------------------------

    @patch("applications.frontend.views.settings")
    def test_named_report_returns_201(self, mock_settings):
        """A valid non-anonymous report returns HTTP 201 with status SUCCESS."""
        mock_settings.BASE.get_github_api.return_value = MagicMock()

        payload = {
            "insult_reference_id": self.insult.reference_id,
            "anonymous": False,
            "reporter_first_name": "Jane",
            "reporter_last_name": "Doe",
            "review_type": InsultReview.REVIEW_TYPE.RECLASSIFY,
            "rationale_for_review": _RATIONALE,
        }
        resp = _post(self.factory, payload)

        self.assertEqual(resp.status_code, status.HTTP_201_CREATED)
        self.assertEqual(resp.data["status"], "SUCCESS")

    @patch("applications.frontend.views.settings")
    def test_named_report_calls_create_issue(self, mock_settings):
        """A valid non-anonymous report calls GitHub create_issue() exactly once."""
        mock_gh = MagicMock()
        mock_settings.BASE.get_github_api.return_value = mock_gh

        payload = {
            "insult_reference_id": self.insult.reference_id,
            "anonymous": False,
            "reporter_first_name": "Jane",
            "reporter_last_name": "Doe",
            "review_type": InsultReview.REVIEW_TYPE.RECLASSIFY,
            "rationale_for_review": _RATIONALE,
        }
        _post(self.factory, payload)

        mock_gh.create_issue.assert_called_once()

    # ------------------------------------------------------------------
    # GitHub issue content
    # ------------------------------------------------------------------

    @patch("applications.frontend.views.settings")
    def test_github_issue_title_contains_reference_id_and_review_type(
        self, mock_settings
    ):
        """The GitHub issue title embeds the insult reference_id and review_type."""
        mock_gh = MagicMock()
        mock_settings.BASE.get_github_api.return_value = mock_gh

        review_type = InsultReview.REVIEW_TYPE.RECATEGORIZE
        payload = {
            "insult_reference_id": self.insult.reference_id,
            "anonymous": True,
            "review_type": review_type,
            "rationale_for_review": _RATIONALE,
        }
        resp = _post(self.factory, payload)

        # Confirm the request succeeded before inspecting the call
        self.assertEqual(resp.status_code, status.HTTP_201_CREATED)
        self.assertIsNotNone(
            mock_gh.create_issue.call_args,
            "create_issue() was never called — check view logic.",
        )

        positional_args, _ = mock_gh.create_issue.call_args
        issue_title = positional_args[0]

        self.assertIn(self.insult.reference_id, issue_title)
        self.assertIn(review_type, issue_title)

    @patch("applications.frontend.views.settings")
    def test_github_issue_body_equals_rationale(self, mock_settings):
        """The GitHub issue body is the verbatim rationale_for_review text."""
        mock_gh = MagicMock()
        mock_settings.BASE.get_github_api.return_value = mock_gh

        payload = {
            "insult_reference_id": self.insult.reference_id,
            "anonymous": True,
            "review_type": InsultReview.REVIEW_TYPE.REMOVAL,
            "rationale_for_review": _RATIONALE,
        }
        resp = _post(self.factory, payload)

        # Confirm the request succeeded before inspecting the call
        self.assertEqual(resp.status_code, status.HTTP_201_CREATED)
        self.assertIsNotNone(
            mock_gh.create_issue.call_args,
            "create_issue() was never called — check view logic.",
        )

        _, keyword_args = mock_gh.create_issue.call_args
        self.assertEqual(keyword_args["body"], _RATIONALE)

    # ------------------------------------------------------------------
    # Validation failures → HTTP 400, GitHub NOT called
    # ------------------------------------------------------------------

    @patch("applications.frontend.views.settings")
    def test_short_rationale_returns_400(self, mock_settings):
        """A rationale shorter than 70 characters returns HTTP 400."""
        mock_gh = MagicMock()
        mock_settings.BASE.get_github_api.return_value = mock_gh

        payload = {
            "insult_reference_id": self.insult.reference_id,
            "anonymous": True,
            "review_type": InsultReview.REVIEW_TYPE.REMOVAL,
            "rationale_for_review": "Too short.",
        }
        resp = _post(self.factory, payload)

        self.assertEqual(resp.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertEqual(resp.data["status"], "FAILED")
        mock_gh.create_issue.assert_not_called()

    @patch("applications.frontend.views.settings")
    def test_non_anonymous_missing_first_name_returns_400(self, mock_settings):
        """Non-anonymous submission without first_name returns HTTP 400."""
        mock_gh = MagicMock()
        mock_settings.BASE.get_github_api.return_value = mock_gh

        payload = {
            "insult_reference_id": self.insult.reference_id,
            "anonymous": False,
            "reporter_last_name": "Doe",
            # reporter_first_name intentionally omitted
            "review_type": InsultReview.REVIEW_TYPE.RECLASSIFY,
            "rationale_for_review": _RATIONALE,
        }
        resp = _post(self.factory, payload)

        self.assertEqual(resp.status_code, status.HTTP_400_BAD_REQUEST)
        mock_gh.create_issue.assert_not_called()

    @patch("applications.frontend.views.settings")
    def test_non_anonymous_missing_last_name_returns_400(self, mock_settings):
        """Non-anonymous submission without last_name returns HTTP 400."""
        mock_gh = MagicMock()
        mock_settings.BASE.get_github_api.return_value = mock_gh

        payload = {
            "insult_reference_id": self.insult.reference_id,
            "anonymous": False,
            "reporter_first_name": "Jane",
            # reporter_last_name intentionally omitted
            "review_type": InsultReview.REVIEW_TYPE.RECLASSIFY,
            "rationale_for_review": _RATIONALE,
        }
        resp = _post(self.factory, payload)

        self.assertEqual(resp.status_code, status.HTTP_400_BAD_REQUEST)
        mock_gh.create_issue.assert_not_called()

    @patch("applications.frontend.views.settings")
    def test_contact_requested_without_email_returns_400(self, mock_settings):
        """post_review_contact_desired=True without reporter_email returns HTTP 400."""
        mock_gh = MagicMock()
        mock_settings.BASE.get_github_api.return_value = mock_gh

        payload = {
            "insult_reference_id": self.insult.reference_id,
            "anonymous": True,
            "post_review_contact_desired": True,
            # reporter_email intentionally omitted
            "review_type": InsultReview.REVIEW_TYPE.REMOVAL,
            "rationale_for_review": _RATIONALE,
        }
        resp = _post(self.factory, payload)

        self.assertEqual(resp.status_code, status.HTTP_400_BAD_REQUEST)
        mock_gh.create_issue.assert_not_called()

    @patch("applications.frontend.views.settings")
    def test_invalid_reference_id_returns_400(self, mock_settings):
        """An unknown insult reference_id returns HTTP 400."""
        mock_gh = MagicMock()
        mock_settings.BASE.get_github_api.return_value = mock_gh

        payload = {
            "insult_reference_id": "INVALID_REF_DOES_NOT_EXIST",
            "anonymous": True,
            "review_type": InsultReview.REVIEW_TYPE.REMOVAL,
            "rationale_for_review": _RATIONALE,
        }
        resp = _post(self.factory, payload)

        self.assertEqual(resp.status_code, status.HTTP_400_BAD_REQUEST)
        mock_gh.create_issue.assert_not_called()

    # ------------------------------------------------------------------
    # GitHub API failure → HTTP 422
    # ------------------------------------------------------------------

    @patch("applications.frontend.views.settings")
    def test_github_api_failure_returns_422(self, mock_settings):
        """When GitHub's API raises an exception the view returns HTTP 422."""
        mock_gh = MagicMock()
        mock_gh.create_issue.side_effect = Exception("GitHub API unavailable")
        mock_settings.BASE.get_github_api.return_value = mock_gh

        payload = {
            "insult_reference_id": self.insult.reference_id,
            "anonymous": True,
            "review_type": InsultReview.REVIEW_TYPE.REMOVAL,
            "rationale_for_review": _RATIONALE,
        }
        resp = _post(self.factory, payload)

        self.assertEqual(resp.status_code, status.HTTP_422_UNPROCESSABLE_ENTITY)
        self.assertIn("FAILED", resp.data["status"])

    @patch("applications.frontend.views.settings")
    def test_github_api_failure_still_calls_create_issue(self, mock_settings):
        """Even on GitHub failure, create_issue() was attempted exactly once."""
        mock_gh = MagicMock()
        mock_gh.create_issue.side_effect = Exception("timeout")
        mock_settings.BASE.get_github_api.return_value = mock_gh

        payload = {
            "insult_reference_id": self.insult.reference_id,
            "anonymous": True,
            "review_type": InsultReview.REVIEW_TYPE.REMOVAL,
            "rationale_for_review": _RATIONALE,
        }
        _post(self.factory, payload)

        mock_gh.create_issue.assert_called_once()


# ---------------------------------------------------------------------------
# Unit tests for the format_issue() helper
# ---------------------------------------------------------------------------


class FormatIssueTests(TestCase):
    """Unit tests for ReportJokeView.format_issue()."""

    def setUp(self):
        cache.clear()
        self.view = ReportJokeView()

    def _sample_data(self, ref_id="SNICKER_ABC1", review_type="RX"):
        return {
            "insult_reference_id": ref_id,
            "review_type": review_type,
            "rationale_for_review": _RATIONALE,
            "anonymous": True,
        }

    def test_returns_both_required_keys(self):
        """format_issue() always returns 'issue_title' and 'issue_body'."""
        result = self.view.format_issue(self._sample_data())
        self.assertIn("issue_title", result)
        self.assertIn("issue_body", result)

    def test_title_contains_reference_id(self):
        """issue_title includes the insult's reference_id."""
        ref_id = "GIGGLE_XYZ9"
        result = self.view.format_issue(self._sample_data(ref_id=ref_id))
        self.assertIn(ref_id, result["issue_title"])

    def test_title_contains_review_type(self):
        """issue_title includes the review_type value."""
        review_type = "RE"
        result = self.view.format_issue(self._sample_data(review_type=review_type))
        self.assertIn(review_type, result["issue_title"])

    def test_body_equals_rationale(self):
        """issue_body is exactly the rationale_for_review text."""
        result = self.view.format_issue(self._sample_data())
        self.assertEqual(result["issue_body"], _RATIONALE)

    def test_raises_value_error_for_non_dict(self):
        """format_issue() raises ValueError when not given a dict."""
        with self.assertRaises(ValueError):
            self.view.format_issue("not a dict")

    def test_raises_value_error_for_none(self):
        """format_issue() raises ValueError when passed None."""
        with self.assertRaises(ValueError):
            self.view.format_issue(None)
