# -*- coding: utf-8 -*-
# Generated by Django 4.2.6 on 2023-11-02 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InsultReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("insult_id", models.IntegerField()),
                ("anonymous", models.BooleanField(default=False)),
                (
                    "reporter_first_name",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "reporter_last_name",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("post_review_contact_desired", models.BooleanField(default=False)),
                (
                    "reporter_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("date_submitted", models.DateField(auto_now=True)),
                ("date_reviewed", models.DateField(blank=True, null=True)),
                ("rationale_for_review", models.TextField()),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("RE", "Joke Reclassification"),
                            ("RC", "Joke Recatagorizion"),
                            ("RX", "Joke Removal"),
                        ]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("P", "Pending"),
                            ("NCE", "Completed - New Explicity Setting"),
                            ("SCE", "Completed - No New Explicity Setting"),
                            ("NJC", "Completed - Assigned to New Catagory"),
                            ("SJC", "Completed - No New Catagory Assigned"),
                            ("X", "Completed - Joke Removed"),
                        ],
                        default="P",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Joke Needing Review",
                "verbose_name_plural": "Jokes Needing Review",
                "db_table": "reported_jokes",
                "ordering": ["status", "-date_submitted"],
                "get_latest_by": ["-date_submitted"],
            },
        ),
        migrations.CreateModel(
            name="Insult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        error_messages="Insults must have content", max_length=65535
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("P", "Poor"),
                            ("F", "Fat"),
                            ("U", "Ugly"),
                            ("S", "Stupid/Dumb"),
                            ("SNWF", "Snowflake"),
                            ("O", "Old"),
                            ("DO", "Old/Daddy"),
                            ("DS", "Stupid/Daddy"),
                            ("N", "Nasty"),
                            ("T", "Stupid/Dumb"),
                            ("TEST", "Testing"),
                            ("SKN", "Skinny"),
                            ("B", "Bald"),
                            ("H", "Hairy"),
                            ("L", "Lazy"),
                            ("SRT", "Short"),
                        ],
                        max_length=5,
                    ),
                ),
                ("explicit", models.BooleanField(default=False)),
                ("added_on", models.DateField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Active"),
                            ("X", "Inactive/Removed"),
                            ("P", "Pending"),
                            ("R", "Rejected"),
                        ],
                        default="P",
                        max_length=2,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Insult/Joke",
                "verbose_name_plural": "Insults/Jokes",
                "db_table": "insults",
                "ordering": ["explicit", "category"],
                "managed": True,
                "indexes": [
                    models.Index(fields=["id"], name="pk_idx"),
                    models.Index(fields=["category"], name="category_idx"),
                    models.Index(fields=["added_by"], name="creator_idx"),
                ],
            },
        ),
    ]
