# Generated by Django 5.0.7 on 2024-09-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insultreview",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P", "Pending"),
                    ("NCE", "Completed - New Explicitly Setting"),
                    ("SCE", "Completed - No New Explicitly Setting"),
                    ("NJC", "Completed - Assigned to New Category"),
                    ("SJC", "Completed - No New Category Assigned"),
                    ("X", "Completed - Joke Removed"),
                ],
                default="P",
                null=True,
            ),
        ),
    ]
