# -*- coding: utf-8 -*-
# Generated by Django 4.2.6 on 2023-10-23 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0004_alter_insultreview_insult_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insultreview",
            name="insult_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="API.insult"
            ),
        ),
    ]
