# -*- coding: utf-8 -*-
# Generated by Django 4.2.6 on 2023-10-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0006_alter_insult_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="insult",
            index=models.Index(fields=["id"], name="pk_idx"),
        ),
        migrations.AddIndex(
            model_name="insult",
            index=models.Index(fields=["category"], name="category_idx"),
        ),
        migrations.AddIndex(
            model_name="insult",
            index=models.Index(fields=["added_by"], name="creator_idx"),
        ),
    ]
