# Generated by Django 5.0.6 on 2024-07-09 22:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0006_alter_insult_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="insult",
            index=models.Index(fields=["category"], name="idx_category"),
        ),
        migrations.AddIndex(
            model_name="insult",
            index=models.Index(
                fields=["category", "explicit"], name="idx_explicit_category"
            ),
        ),
        migrations.AddIndex(
            model_name="insult",
            index=models.Index(fields=["explicit"], name="idx_explicit"),
        ),
        migrations.AddIndex(
            model_name="insult",
            index=models.Index(fields=["added_by"], name="idx_added_by"),
        ),
    ]
