# -*- coding: utf-8 -*-
# Generated by Django 4.2.6 on 2023-10-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0007_insult_pk_idx_insult_category_idx_insult_creator_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insultreview",
            name="insult_id",
            field=models.IntegerField(),
        ),
    ]
