output-format: json

strictness: medium
test-warnings: true
doc-warnings: false
member-warnings: false
inherits:
  - default
ignore-paths:
  - docs
ignore-patterns:
  - (^|/)skip(this)?(/|$)
autodetect: true
max-line-length: 300

bandit:
  run: true
  options:
    config: .bandit.yml

dodgy:
  run: true

frosted:
  disable:
    - E103
    - E306

mccabe:
  run: false
  options:
    max-complexity: 10

pycodestyle:
  disable:
    - W602
    - W603
    - E226
    - E302
    - E71
    - W292
    - W391
  options:
    max-line-length: 300

pydocstyle:
  disable:
    - D100
    - D101

pyflakes:
  disable:
    - F403
    - F810

pylint:
  load-plugins:
    - pylint_django
  disable:
    - bad-builtin
    - too-few-public-methods
    - raw-checker-failed
    - bad-inline-option
    - locally-disabled
    - file-ignored
    - suppressed-message
    - useless-suppression
    - deprecated-pragma
    - use-symbolic-message-instead
    - too-many-instance-attributes
    - len-as-condition
    - too-few-public-methods,
    - anomalous-backslash-in-string,
    - no-else-return,
    - simplifiable-if-statement,
    - too-many-arguments,

  options:
    max-locals: 15
    max-returns: 6
    max-branches: 15
    max-statements: 60
    max-parents: 7
    max-attributes: 7
    min-public-methods: 1
    max-public-methods: 20
    max-module-lines: 1000
    max-line-length: 300

pyroma:
  disable:
    - PYR15
    - PYR18

pyright:
  venv-path: /workspaces/the-dozens-django/.venv
  options:
    level: warning
    pythonversion: 3.7
    skipunannotated: true

mypy:
  run: true
  options:
    ignore-missing-imports: true
    follow-imports: skip

vulture:
  run: true
