# Generated by Django 5.1.6 on 2025-08-07 18:10

import django.db.models.deletion
import django_prometheus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InsultCategory",
            fields=[
                (
                    "category_key",
                    models.CharField(
                        max_length=5, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Insult Category",
                "verbose_name_plural": "Insult Categories",
                "db_table": "insult_categories",
                "ordering": ["name"],
                "managed": True,
                "indexes": [
                    models.Index(fields=["category_key"], name="idx_category_key"),
                    models.Index(fields=["name"], name="idx_name"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category_key", "name"), name="unique_category_key_name"
                    )
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "insult_categories"
                ),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Insult",
            fields=[
                (
                    "content",
                    models.CharField(
                        error_messages={"required": "Insults must have content"},
                        max_length=65535,
                    ),
                ),
                ("insult_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "reference_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Unique identifier for the insult, generated from the primary key.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("nsfw", models.BooleanField(default=False)),
                ("added_on", models.DateField(auto_now_add=True)),
                (
                    "reports_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Active"),
                            ("X", "Inactive/Removed"),
                            ("P", "Pending"),
                            ("R", "Rejected"),
                        ],
                        db_index=True,
                        default="P",
                        max_length=2,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="API.insultcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insult/Joke",
                "verbose_name_plural": "Insults/Jokes",
                "db_table": "insults",
                "ordering": ["nsfw", "category"],
                "managed": True,
                "indexes": [
                    models.Index(fields=["category"], name="idx_category"),
                    models.Index(fields=["category", "nsfw"], name="idx_nsfw_category"),
                    models.Index(fields=["nsfw"], name="idx_nsfw"),
                    models.Index(fields=["added_by"], name="idx_added_by"),
                    models.Index(fields=["reference_id"], name="idx_reference_id"),
                    models.Index(
                        fields=["reference_id", "insult_id"], name="idx_reference_id_pk"
                    ),
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("insult"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="InsultReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("insult_reference_id", models.CharField(max_length=50)),
                ("anonymous", models.BooleanField(default=False)),
                (
                    "reporter_first_name",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "reporter_last_name",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("post_review_contact_desired", models.BooleanField(default=False)),
                (
                    "reporter_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("date_submitted", models.DateField(auto_now=True)),
                ("date_reviewed", models.DateField(blank=True, null=True)),
                ("rationale_for_review", models.TextField()),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("RE", "Joke Reclassification"),
                            ("RC", "Joke Recategorization"),
                            ("RX", "Joke Removal"),
                        ]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("NCE", "Completed - New Explicitly Setting"),
                            ("SCE", "Completed - No New Explicitly Setting"),
                            ("NJC", "Completed - Assigned to New Category"),
                            ("SJC", "Completed - No New Category Assigned"),
                            ("X", "Completed - Joke Removed"),
                        ],
                        default="P",
                        max_length=3,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Joke Needing Review",
                "verbose_name_plural": "Jokes Needing Review",
                "db_table": "reported_jokes",
                "ordering": ["status", "-date_submitted"],
                "get_latest_by": ["-date_submitted"],
                "indexes": [
                    models.Index(fields=["review_type"], name="idx_review_type"),
                    models.Index(fields=["status"], name="idx_status"),
                    models.Index(fields=["date_submitted"], name="idx_date_submitted"),
                    models.Index(fields=["date_reviewed"], name="idx_date_reviewed"),
                    models.Index(fields=["reviewer"], name="idx_reviewer"),
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("jokeReview"),
                models.Model,
            ),
        ),
    ]
