# Generated by Django 5.1.6 on 2025-08-13 23:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="insult",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Active"),
                    ("X", "Inactive/Removed"),
                    ("P", "Pending - New"),
                    ("R", "Rejected"),
                    ("F", "Flagged for Review"),
                ],
                db_index=True,
                default="P",
                max_length=2,
            ),
        ),
        migrations.AddIndex(
            model_name="insult",
            index=models.Index(
                fields=["added_by", "status", "category"], name="idx_added_status_cat"
            ),
        ),
        migrations.AddIndex(
            model_name="insultreview",
            index=models.Index(
                fields=["insult_reference_id"], name="idx_insult_reference_id"
            ),
        ),
    ]
