# Generated by Django 5.1.6 on 2025-08-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="insultcategory",
            options={
                "managed": True,
                "ordering": ["name"],
                "verbose_name": "Insult Category",
                "verbose_name_plural": "Insult Categories",
            },
        ),
        migrations.AlterUniqueTogether(
            name="insultcategory",
            unique_together={("category_key", "name")},
        ),
        migrations.AddIndex(
            model_name="insultcategory",
            index=models.Index(fields=["category_key"], name="idx_category_key"),
        ),
        migrations.AddIndex(
            model_name="insultcategory",
            index=models.Index(fields=["name"], name="idx_name"),
        ),
        migrations.AlterModelTable(
            name="insultcategory",
            table="insult_categories",
        ),
    ]
