# Generated by Django 5.1.6 on 2025-08-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0002_alter_insultcategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="insult",
            name="reports_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
