# Generated by Django 5.1.6 on 2025-08-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0002_alter_insult_status_insult_idx_added_status_cat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insult",
            name="reference_id",
            field=models.CharField(
                blank=True,
                db_comment="Unique reference ID for the insult, generated from the primary key.",
                db_index=True,
                editable=False,
                help_text="Unique identifier for the insult, generated from the primary key.",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Reference ID",
            ),
        ),
    ]
