# Generated by Django 5.1.6 on 2025-08-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0003_alter_insult_reference_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insult",
            name="reports_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
