# Generated by Django 5.1.6 on 2025-08-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0004_alter_insult_reports_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insult",
            name="reports_count",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
