# Generated by Django 5.1.6 on 2025-08-14 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0005_alter_insult_reports_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="insultreview",
            name="insult",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="API.insult",
            ),
        ),
    ]
