# Generated by Django 5.1.6 on 2025-08-17 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0006_insultreview_insult"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="insultreview",
            index=models.Index(
                fields=["insult", "insult_reference_id"], name="idx_insult)_ref_id"
            ),
        ),
    ]
