# Generated by Django 5.2.5 on 2025-09-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0007_insultreview_idx_insult__ref_id"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="insultreview",
            new_name="idx_insult_ref_id",
            old_name="idx_insult)_ref_id",
        ),
        migrations.AlterField(
            model_name="insult",
            name="nsfw",
            field=models.BooleanField(),
        ),
    ]
