# Generated by Django 5.2.5 on 2025-09-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0008_rename_idx_insult__ref_id_idx_insult_ref_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="insultcategory",
            name="description",
            field=models.CharField(default=" ", max_length=50000),
            preserve_default=False,
        ),
    ]
