# Generated by Django 5.2.5 on 2025-10-21 03:28

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0009_insultcategory_description"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="insult",
            managers=[
                ("public", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="insultcategory",
            managers=[
                ("public", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "theme_key",
                    models.CharField(
                        max_length=5, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("theme_name", models.CharField(max_length=255, unique=True)),
                ("description", models.CharField(max_length=50000)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme",
                        to="API.insultcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Theme",
                "verbose_name_plural": "Themes",
                "db_table": "themes",
                "ordering": ["theme_name"],
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="insult",
            name="theme",
            field=models.ForeignKey(
                default="INTL",
                on_delete=django.db.models.deletion.PROTECT,
                to="API.theme",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="theme",
            index=models.Index(fields=["theme_key"], name="idx_theme_key"),
        ),
        migrations.AddIndex(
            model_name="theme",
            index=models.Index(fields=["theme_name"], name="idx_theme_name"),
        ),
        migrations.AddConstraint(
            model_name="theme",
            constraint=models.UniqueConstraint(
                fields=("theme_key", "theme_name"), name="unique_theme_key_name"
            ),
        ),
    ]
