# Generated by Django 5.2.5 on 2025-10-21 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0010_alter_insult_managers_alter_insultcategory_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="category",
        ),
        migrations.AddField(
            model_name="insultcategory",
            name="theme",
            field=models.ForeignKey(
                default="APP",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="theme",
                to="API.theme",
            ),
            preserve_default=False,
        ),
    ]
