# Generated by Django 5.2.5 on 2025-10-21 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0011_remove_theme_category_insultcategory_theme"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="insult",
            name="content",
            field=models.TextField(
                error_messages={"required": "Insults must have content"}
            ),
        ),
        migrations.AlterField(
            model_name="insult",
            name="reports_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="insultcategory",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="insultcategory",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insult_categories",
                to="API.theme",
            ),
        ),
        migrations.AlterField(
            model_name="insultreview",
            name="review_type",
            field=models.CharField(
                choices=[
                    ("RE", "Joke Reclassification"),
                    ("RC", "Joke Recategorization"),
                    ("RX", "Joke Removal"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="description",
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name="insultreview",
            index=models.Index(
                fields=["status", "-date_submitted"], name="idx_status_date_sub"
            ),
        ),
    ]
