# Generated by Django 5.2.11 on 2026-03-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0012_alter_insult_content_alter_insult_reports_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insult",
            name="reports_count",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="insultreview",
            name="review_type",
            field=models.CharField(
                choices=[
                    ("RE", "Joke Reclassification"),
                    ("RC", "Joke Recategorization"),
                    ("RX-Q", "Joke Removal - Quality Issue"),
                    ("RX-D", "Joke Removal - Duplicate"),
                    ("RX-M", "Joke Removal - Malicious"),
                ],
                max_length=4,
            ),
        ),
    ]
