# Generated by Django 6.0.8 on 2026-09-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0013_alter_insult_reports_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="insult",
            name="is_admin_modified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="insult",
            name="modified_content",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insult",
            name="reviewer_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
