# Generated by Django 6.0.8 on 2026-09-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0014_insult_is_admin_modified_insult_modified_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insult",
            name="is_admin_modified",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
