# Generated by Django 6.0.8 on 2026-09-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0015_alter_insult_is_admin_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insult",
            name="modified_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
