# Generated by Django 6.0.8 on 2026-09-30 20:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0016_alter_insult_modified_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalInsult",
            fields=[
                (
                    "content",
                    models.TextField(
                        error_messages={"required": "Insults must have content"}
                    ),
                ),
                ("insult_id", models.IntegerField(blank=True, db_index=True)),
                (
                    "is_admin_modified",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("modified_content", models.TextField(blank=True, null=True)),
                ("reviewer_notes", models.TextField(blank=True, null=True)),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        db_comment="Unique reference ID for the insult, generated from the primary key.",
                        db_index=True,
                        editable=False,
                        help_text="Unique identifier for the insult, generated from the primary key.",
                        max_length=50,
                        null=True,
                        verbose_name="Reference ID",
                    ),
                ),
                ("nsfw", models.BooleanField()),
                ("added_on", models.DateField(blank=True, editable=False)),
                ("reports_count", models.PositiveIntegerField(default=0, null=True)),
                (
                    "last_modified",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Active"),
                            ("X", "Inactive/Removed"),
                            ("P", "Pending - New"),
                            ("R", "Rejected"),
                            ("F", "Flagged for Review"),
                        ],
                        db_index=True,
                        default="P",
                        max_length=2,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="API.insultcategory",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="API.theme",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Insult/Joke",
                "verbose_name_plural": "historical Insults/Jokes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInsultReview",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("insult_reference_id", models.CharField(max_length=50)),
                ("anonymous", models.BooleanField(default=False)),
                (
                    "reporter_first_name",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "reporter_last_name",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("post_review_contact_desired", models.BooleanField(default=False)),
                (
                    "reporter_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("date_submitted", models.DateField(blank=True, editable=False)),
                ("date_reviewed", models.DateField(blank=True, null=True)),
                ("rationale_for_review", models.TextField()),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("RE", "Joke Reclassification"),
                            ("RC", "Joke Recategorization"),
                            ("RX-Q", "Joke Removal - Quality Issue"),
                            ("RX-D", "Joke Removal - Duplicate"),
                            ("RX-M", "Joke Removal - Malicious"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("NCE", "Completed - New Explicitly Setting"),
                            ("SCE", "Completed - No New Explicitly Setting"),
                            ("NJC", "Completed - Assigned to New Category"),
                            ("SJC", "Completed - No New Category Assigned"),
                            ("X", "Completed - Joke Removed"),
                        ],
                        default="P",
                        max_length=3,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "insult",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="API.insult",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Joke Needing Review",
                "verbose_name_plural": "historical Jokes Needing Review",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
